apiVersion: apps/v1

kind: Deployment

metadata:
  name: flask-app

  namespace: self-healing

spec:

  replicas: 3

  selector:

    matchLabels:

      app: flask

  template:

    metadata:

      labels:

        app: flask-app

    spec:

      containers:

      - name: flask

        image: self-healing-demo:latest

        imagePullPolicy: Never

        ports:

        - containerPort: 5001

        readinessProbe:

          httpGet:

            path: /health

            port: 5001

          initialDelaySeconds: 5

        livenessProbe:

          httpGet:

            path: /health

            port: 5001

          initialDelaySeconds: 10
